# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Ryan Antonio <ryan.antonio@esat.kuleuven.be>

APP     = dma-2d-test
SRCS    = src/dma-2d-test.c
INCDIRS = data
INCDIRS += ../../snax/gemm/include
RISCV_LDFLAGS += ../../snax/gemm/build/snax-gemm-lib.o

include ../common.mk
